name: Deploy website

on:
  push:
    branches: [ "master" ]
    paths:
      - ".github/workflows/deploy-website.yml"
      - "wwwroot/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Call hook
      env:
        CF_PAGES_HOOKURL: ${{ secrets.CF_PAGES_HOOKURL }}
      run: curl -X POST $CF_PAGES_HOOKURL
