name: TTF Builder

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/generate-ttf.yml"
      - "build/**"
      - "raw/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install requirements
        run: build/_install_reqs_ubuntu.sh

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run file copy tool
        run: |
          cd build
          dotnet run

      - name: Run svgs2ttf
        run: |
          cd build
          svgs2ttf/svgs2ttf metadata.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sakamata-font
          path: build/*.ttf

      - name: Set current datetime as env variable
        env:
          TZ: "Etc/UTC"
        run: echo "DTIME=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Pre Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: v${{ env.CURRENT_DATETIME }}
          files: build/*.ttf
