name: TTF Builder

on:
  push:
    paths:
      - ".github/workflows/generate-ttf.yml"
      - "build/**"
      - "chart-generator/**"
      - "raw/**"
      - "gen-release-message/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install requirements
        run: build/_install_reqs_ubuntu.sh

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run build
        run: |
          cd build
          dotnet run

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sakamata-font
          path: |
            build/*.ttf
            build/*.sources.tsv

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: |
          echo "DTIME=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Generate (Pre)Release Message
        run: |
          cd gen-release-message
          dotnet run ../build/sakamata-v1.sources.tsv

      - name: Pre Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          prerelease: true
          tag_name: v${{ env.DTIME }}
          body_path: gen-release-message/message.md
          files: |
            build/*.ttf
            build/*.sources.tsv
