name: TTF Builder

on:
  push:
    paths:
      - ".github/workflows/generate-ttf.yml"
      - ".github/actions/build-ttf/action.yml"
      - "raw/**"
      - "gen-release-message/**"

  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        weight: [0, 100, 300, 400, 500, 700, 900]
        strict: ["strict", "nostrict"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: mkaraki/Png2Font/.github/actions/build-ttf
        with:
          filename-prefix: sakamata-font
          fontname: Sakamata Font
          weight: ${{ matrix.weight }}
          strict: ${{ matrix.strict }}
          builder-version: master

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Copy files
        run: |
          mkdir fonts
          cp artifacts/**/*.ttf fonts/
          cp artifacts/**/*.sources.tsv fonts/

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: |
          echo "DTIME=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      - name: Generate (Pre)Release Message
        run: |
          cd gen-release-message
          dotnet run ../fonts/sakamata-font-0-nostrict.sources.tsv

      - name: Copy release note
        run: |
          cp gen-release-message/message.md fonts/release-note.md

      - uses: actions/upload-artifact@v4
        with:
          name: sakamata-font
          path: fonts

      - name: Pre Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          prerelease: true
          tag_name: v${{ env.DTIME }}
          body_path: gen-release-message/message.md
          files: |
            fonts/*.ttf
            fonts/*.sources.tsv
