name: TTF Builder

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/generate-ttf.yml"
      - "build/**"
      - "raw/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install requirements
        run: build/_install_reqs_ubuntu.sh

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run file copy tool
        run: |
          cd build
          dotnet run

      - name: Run svgs2ttf
        run: |
          cd build
          svgs2ttf/svgs2ttf metadata.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sakamata-font
          path: build/*.ttf

  release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !contains(github.event.commits.*.message, '[skip release]') }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sakamata-font
          path: build

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: |
          echo "DTIME=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
          echo "NOWTIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Pre Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          prerelease: true
          tag_name: v${{ env.DTIME }}
          body: |
            このリリースは${{ env.NOWTIME }}時点のデータを利用したリリースです。安定版ではありません。

            このプロジェクトはホロライブ二次創作ガイドラインに準拠して実施されています。
            成果物はホロライブ二次創作ガイドラインの範囲でのみ利用が可能です。
          files: build/*.ttf
